pipeline {
    agent any
    tools {
            jdk 'Java17'
    }
    stages{
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Which Java?') {
            steps {
                sh 'java --version'
            }
        }
        stage('test'){
            steps{
                //run app tests using gradle
                dir('fluxedu') {
                      sh "pwd"
                      sh './gradlew test'
                }
            }
        }
        stage('build'){
            steps{
                dir('fluxedu') {
                      sh "pwd"
                      sh './gradlew clean build'
                }
            }
        }
    }

    post{
        success{
            echo 'Sukces'
        }
    }
}