pipeline {
    agent any
    stages{
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('build'){
            steps{
                sh 'echo "xx"'
                sh 'pwd'
                sh 'ls'
                sh './gradlew clean build'
            }
        }
        stage('test'){
            steps{
                //run app tests using gradle
                sh './gradlew test'
            }
        }
    }

    post{
        success{
            echo 'Sukces'
        }
    }
}