pipeline {
    agent any
    tools {
            jdk 'Java17'
    }
    stages{
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Which Java?') {
            steps {
                sh 'java --version'
            }
        }        
        stage('build'){
            steps{
                sh 'echo "xx"'
                sh 'pwd'
                sh 'ls'
                dir('fluxedu') {
                      sh "pwd"
                      sh 'ls'
                      sh './gradlew clean build'
                }
            }
        }
        stage('test'){
            steps{
                //run app tests using gradle
                sh 'cd fluxedu'
                sh './fluxedu/gradlew test'
            }
        }
    }

    post{
        success{
            echo 'Sukces'
        }
    }
}